apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-app
  template:
    metadata:
      labels:
        app: site-app
    spec:
      containers:
      - name: site-app
        image: lidordayan/site-app
        ports:
        - containerPort: 5000

