apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  type: NodePort
  selector:
    app: site-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
